# Generated by Django 3.0.7 on 2020-07-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200720_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_frequency',
            field=models.IntegerField(null=True),
        ),
    ]
