# Generated by Django 3.0.7 on 2020-07-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_slug_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug_frequency',
        ),
    ]
