# Generated by Django 3.0.7 on 2020-08-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200807_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='replied_comment',
        ),
    ]
