# Generated by Django 3.0.7 on 2020-08-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200807_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replied_comment',
            new_name='replied_commentid',
        ),
    ]
