# Generated by Django 3.0.7 on 2020-08-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200808_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replied_commentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repcom', to='post.Comment'),
        ),
    ]
