# Generated by Django 3.0.7 on 2020-09-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='post_images'),
        ),
    ]
