# Generated by Django 3.0.7 on 2020-09-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200909_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
