# Generated by Django 3.0.7 on 2020-10-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20201012_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game_console',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='game_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
